<?php if ( function_exists( 'lazyblocks' ) ) :

    lazyblocks()->add_block( array(
        'id' => 264,
        'title' => 'Link Promo',
        'icon' => 'dashicons dashicons-admin-links',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/link-promo',
        'description' => '',
        'category' => 'common',
        'category_label' => 'common',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'left',
                2 => 'center',
                3 => 'right',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_a368854a44' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Link Title',
                'name' => 'link_title',
                'type' => 'text',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placeholder' => '',
                'help' => '',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_1dfb014878' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Link',
                'name' => 'link',
                'type' => 'url',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placeholder' => '',
                'help' => '',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_c659df4eac' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'External Link',
                'name' => 'external_link',
                'type' => 'checkbox',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'true',
                'placeholder' => '',
                'help' => '',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_eefac84cda' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Link Description',
                'name' => 'link_description',
                'type' => 'rich_text',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placeholder' => '',
                'help' => '',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_dacab04f54' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Link Image',
                'name' => 'link_image',
                'type' => 'image',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placeholder' => '',
                'help' => '',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '{{#if link_image}}

    	<p><a href="{{link}}" {{#if external_link}}target="_blank"{{/if}}><img src="{{link_image.url}}" alt="{{link_title.alt}}">
    </a></p>

    {{/if}}

    <p><a href="{{link}}" {{#if external_link}}target="_blank"{{/if}}><big><strong>{{link_title}}</strong></big></a></p>
    <p>{{{link_description}}}</p>',
            'frontend_callback' => '',
            'frontend_css' => '',
        ),
        'condition' => array(
        ),
    ) );

    lazyblocks()->add_block( array(
        'id' => 259,
        'title' => 'Test Lazy Block',
        'icon' => '',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/test-lazy-block',
        'description' => '',
        'category' => 'common',
        'category_label' => 'common',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_44ebb04652' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'General Text',
                'name' => 'general_text',
                'type' => 'text',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placeholder' => '',
                'help' => '',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_644bb5427e' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Inspector Test',
                'name' => 'inspector_test',
                'type' => 'text',
                'allow_null' => 'false',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placeholder' => '',
                'help' => '',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '<div class="test">
    {{general_text}}
    </div>',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '<div class="test">
    {{general_text}}
    </div>',
            'frontend_callback' => '',
            'frontend_css' => '',
        ),
        'condition' => array(
        ),
    ) );

endif;
